name: CI
on: issue_comment

jobs:
  build_by_issue:
    # This job only runs for issue comments
    name: Build By Issue
    if: github.repository_owner_id == github.actor_id
    runs-on: ubuntu-latest
    steps:
      - uses: DuckSoft/build-aur-action@master
        with:
          repo-name: ${{ github.event.comment.body }}
